services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    container_name: kuanjiapo_web
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql # because we are using links, we can use the service name as the host
    volumes:
      - ./static:/app/static
      - ./src/web.py:/app/web.py
    depends_on:
      - mysql
  detect:
    build:
      context: .
      dockerfile: detect.Dockerfile
    container_name: kuanjiapo_detect
    restart: always
    environment:
      VIDEO_SOURCE: "http://web:8000/static/video/live.m3u8"
      SAVE_API_URL: "http://web:8000/api/save"
    volumes:
      - ./static:/app/static
      - ./src/detect.py:/app/detect.py
      - .env:/app/.env
    depends_on:
      - web
  mysql:
    image: mysql:8.0
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mysql
  nginx-rtmp:
    image: alfg/nginx-rtmp
    container_name: kuanjiapo_nginx_rtmp
    # restart: always
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template
  ffmpeg:
    image: jrottenberg/ffmpeg
    command: -re -f video4linux2 -i /dev/video0 -vcodec libx264 -pix_fmt yuv420p -preset ultrafast -f hls -hls_time 2 -hls_list_size 3 -hls_flags delete_segments /output/live.m3u8
    volumes:
      - ./static/video/:/output
    devices:
      - "${DEV_VIDEO}:${DEV_VIDEO}"
    depends_on:
      - nginx-rtmp
volumes:
  mysql_data:
