services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kuanjiapo_web
    restart: always
    command: uvicorn web:app --host 0.0.0.0 --port 8000 --ssl-certfile /certs/server.crt --ssl-keyfile /certs/server.key
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql # because we are using links, we can use the service name as the host
      - SSL_CERTFILE=/certs/server.crt
      - SSL_KEYFILE=/certs/server.key
    volumes:
      - ./static:/app/static
      - ./src/web.py:/app/web.py
      - ./certs:/certs:ro
    depends_on:
      - mysql
  detect:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kuanjiapo_detect
    restart: always
    command: python detect.py
    environment:
      SAVE_API_URL: "http://web:8000/api/save"
    volumes:
      - ./static:/app/static
      - ./src/detect.py:/app/detect.py
      - .env:/app/.env
    privileged: true
    devices:
      - /dev:/dev
    depends_on:
      - web
  mysql:
    image: mysql:8.0
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config/mysql_init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mysql
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - web
      - detect
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
volumes:
  mysql_data:
